version: '{build}'

clone_depth: 50

environment:
  MVN_VERSION: 3.5.2

  matrix:
    - platform: x86
      JAVA_HOME: ${ProgramFiles(x86)}\Java\jdk1.8.0
    - platform: x64
      JAVA_HOME: $(ProgramFiles)\Java\jdk1.8.0
    - platform: x64
      JAVA_HOME: $(ChocolateyInstall)\lib\jvm\jdk9

cache:
  - $(ChocolateyInstall)\lib -> .appveyor.yml
  - $(ChocolateyInstall)\bin -> .appveyor.yml

install:
  - ps: If ($env:JAVA_HOME -eq ($env:ChocolateyInstall + '\lib\jvm\jdk9')) { cinst jdk9 -i -params 'installdir=C:\\ProgramData\\chocolatey\\lib\\jvm\\jdk9' }
  - ps: cinst maven -i --version $env:MVN_VERSION
  - cmd: PATH %ChocolateyInstall%\lib\maven\apache-maven-%MVN_VERSION%\bin;%JAVA_HOME%\bin;%PATH%

before_build:
  - java -Xmx32m -version
  - javac -J-Xmx32m -version
  - mvn -version

build_script:
  - mvn clean package
